services:
  db:
    build: ./docker/db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aihelper
    ports:
      - "5410:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    networks:
      - ai_helper_network

  api:
    build: ./docker/api
    restart: always
    depends_on:
      - db
    volumes:
      - ./api:/app
    networks:
      - ai_helper_network

  nginx:
    build: ./docker/nginx
    restart: always
    depends_on:
      - api
    ports:
      - "8001:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/logs/nginx:/var/log/nginx
    networks:
      - ai_helper_network

networks:
  ai_helper_network:
