services:
  # База данных
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${EXTERNAL_DB_PORT}:${DB_PORT}"
    volumes:
      - ./db/docker/entrypoint.sh:/entrypoint.sh
      - ./db/docker/postgresql.conf:/tmp/postgresql.conf
      - ${EXTERNAL_DB_DATA}:/var/lib/postgresql/data
      - ${EXTERNAL_DB_LOGS}:/var/lib/postgresql/data/log
      - ${EXTERNAL_DB_BACKUPS}:/backups
    networks:
      - default

  # API
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - ${SERVICE_DB}
    environment:
      HOST: ${API_HOST}
      PORT: ${API_PORT}
      DB_CONNECTION_URL: ${API_DB_CONNECTION_URL}
      INTEGRATION_GEN_API_BASE_URL: ${API_INTEGRATION_GEN_API_BASE_URL}
      INTEGRATION_GEN_API_KEY: ${API_INTEGRATION_GEN_API_KEY}
    volumes:
      - ./api/docker/entrypoint.sh:/entrypoint.sh
      - ./api:/app
      - ${EXTERNAL_API_LOGS}:/app/logs
      - ${EXTERNAL_API_RUNTIME}:/app/runtime
    networks:
      - default


  # Фронтенд
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      HOST: ${FRONTEND_HOST}
      PORT: ${FRONTEND_PORT}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      FRONTEND_PUBLIC_HOST: ${GATEWAY_FRONTEND_HOST}
      API_BASE_URL: ${FRONTEND_API_BASE_URL}
      API_PUBLIC_HOST: ${GATEWAY_API_HOST}
    depends_on:
      - ${SERVICE_API}
    volumes:
      - ./front/docker/entrypoint.sh:/entrypoint.sh
      - ./front:/app
      - ${EXTERNAL_FRONTEND_LOGS}:/app/logs
    networks:
      - default

  # Главные враты 🙄🤦‍♂️
  gateway:
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - ${SERVICE_API}
      - ${SERVICE_FRONTEND}
    environment:
      API_HOST: ${GATEWAY_API_HOST}
      API_PROXY_PASS: ${GATEWAY_API_PROXY_PASS}
      FRONTEND_HOST: ${GATEWAY_FRONTEND_HOST}
      FRONTEND_PROXY_PASS: ${GATEWAY_FRONTEND_PROXY_PASS}
    ports:
      - "${EXTERNAL_HTTP_PORT}:80"
      - "${EXTERNAL_HTTPS_PORT}:443"
    volumes:
      - ./gateway/docker/entrypoint.sh:/entrypoint.sh
      - ./gateway/docker/default.env.conf:/tmp/default.env.conf:ro
      - ${GATEWAY_API_SSL_CERT}:/etc/nginx/ssl/api.cert:ro
      - ${GATEWAY_API_SSL_KEY}:/etc/nginx/ssl/api.key:ro
      - ${GATEWAY_FRONTEND_SSL_CERT}:/etc/nginx/ssl/front.cert:ro
      - ${GATEWAY_FRONTEND_SSL_KEY}:/etc/nginx/ssl/front.key:ro
      - ${EXTERNAL_GATEWAY_LOGS}:/var/log/nginx
    networks:
      - default

networks:
  default:
    name: ${NETWORK}
    driver: bridge
