services:
  # База данных
  db:
    build:
      context: ./db
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${EXTERNAL_DB_PORT}:${DB_PORT}"
    volumes:
      - ./db/docker/entrypoint.sh:/entrypoint.sh
      - ./db/docker/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./db/data:/var/lib/postgresql/data
      - ${EXTERNAL_DB_LOGS}:/var/lib/postgresql/data/log
    networks:
      - default

  # API
  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - ${SERVICE_DB}
    environment:
      HOST: ${API_HOST}
      PORT: ${API_PORT}
      DB_CONNECTION_URL: ${API_DB_CONNECTION_URL}
      INTEGRATION_GEN_API_BASE_URL: ${API_INTEGRATION_GEN_API_BASE_URL}
      INTEGRATION_GEN_API_KEY: ${API_INTEGRATION_GEN_API_KEY}
    volumes:
      - ./api/docker/entrypoint.sh:/entrypoint.sh
      - ./api:/app
      - ${EXTERNAL_API_LOGS}:/app/logs
      - ${EXTERNAL_API_RUNTIME}:/app/runtime
    networks:
      - default


  # Фронтенд
  front:
    build:
      context: ./front
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      HOST: ${FRONTEND_HOST}
      PORT: ${FRONTEND_PORT}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      API_BASE_URL: ${FRONTEND_API_BASE_URL}
    depends_on:
      - ${SERVICE_API}
    volumes:
      - ./front/docker/entrypoint.sh:/entrypoint.sh
      - ./front:/app
      - ${EXTERNAL_FRONTEND_LOGS}:/app/logs
    networks:
      - default

  # Главные враты 🙄🤦‍♂️
  gateway:
    build:
      context: ./gateway
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - ${SERVICE_API}
      - ${SERVICE_FRONTEND}
    environment:
      API_PUBLIC_HOST: ${GATEWAY_API_PUBLIC_HOST}
      API_PUBLIC_PORT: ${GATEWAY_API_PUBLIC_PORT}
      API_PROXY_PASS: ${GATEWAY_API_PROXY_PASS}
      FRONTEND_PUBLIC_HOST: ${GATEWAY_FRONTEND_PUBLIC_HOST}
      FRONTEND_PUBLIC_PORT: ${GATEWAY_FRONTEND_PUBLIC_PORT}
      FRONTEND_PROXY_PASS: ${GATEWAY_FRONTEND_PROXY_PASS}
    ports:
      - "${EXTERNAL_FRONTEND_PORT}:${GATEWAY_FRONTEND_PUBLIC_PORT}" # Frontend
      - "${EXTERNAL_API_PORT}:${GATEWAY_API_PUBLIC_PORT}" # API
    volumes:
      - ./gateway/docker/entrypoint.sh:/entrypoint.sh
      - ./gateway/docker/default.env.conf:/tmp/default.env.conf:ro
      - ./gateway/ssl:/etc/nginx/ssl:ro
      - ${EXTERNAL_GATEWAY_LOGS}:/var/log/nginx
    networks:
      - default

networks:
  default:
    name: ${NETWORK}
    driver: bridge
