services:
  # Главные враты 🙄🤦‍♂️
  gateway:
    container_name: gateway
    build:
      context: ../../gateway
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - ${SERVICE_API}
      - ${SERVICE_FRONTEND}
    environment:
      API_HOST: ${GATEWAY_API_HOST}
      API_PROXY_PASS: ${GATEWAY_API_PROXY_PASS}
      FRONTEND_HOST: ${GATEWAY_FRONTEND_HOST}
      FRONTEND_PROXY_PASS: ${GATEWAY_FRONTEND_PROXY_PASS}
    ports:
      - "${EXTERNAL_HTTP_PORT}:80"
      - "${EXTERNAL_HTTPS_PORT}:443"
    volumes:
      - ../../gateway/docker/entrypoint.sh:/entrypoint.sh
      - ../../gateway/docker/default.env.conf:/tmp/default.env.conf:ro
      - ${GATEWAY_API_SSL_CERT}:/etc/nginx/ssl/api.cert:ro
      - ${GATEWAY_API_SSL_KEY}:/etc/nginx/ssl/api.key:ro
      - ${GATEWAY_FRONTEND_SSL_CERT}:/etc/nginx/ssl/front.cert:ro
      - ${GATEWAY_FRONTEND_SSL_KEY}:/etc/nginx/ssl/front.key:ro
      - ${EXTERNAL_GATEWAY_LOGS}:/var/log/nginx
    networks:
      - aidrom-network

# networks:
#   aidrom-network:
#     name: ${NETWORK}
#     driver: bridge
#     external: true
